
language: android
jdk: oraclejdk8
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-preview-license'
    - 'android-sdk-license-.+'
    - 'android-sdk-license'
    - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    
    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
